### ISSUE TITLE
Receiving this error recently

### ISSUE THREAD

**Issue by Payton-Lang** [harryy-he/finqual#2]
Entered these instructions:

>>> from finqual import finqual as fq
>>> fq.Ticker("TSLA").income(2020,2022)

This is what was returned:

Traceback (most recent call last):
  File "C:\Users\Payton\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Payton\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Payton\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Payton\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Payton\AppData\Local\Programs\Python\Python311\Lib\site-packages\finqual\finqual.py", line 68, in __init__
    self.cik = self.CIK()
               ^^^^^^^^^^
  File "C:\Users\Payton\AppData\Local\Programs\Python\Python311\Lib\site-packages\finqual\finqual.py", line 80, in CIK
    cik = source.json()
          ^^^^^^^^^^^^^
  File "C:\Users\Payton\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by harryy-he** [comment]
Have fixed in version 1.5.0, thanks for alerting!
